name: sfxp_meetup
description: SFXP Meetup

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flare_flutter: ^2.0.1
  shake: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/mock/
    - assets/animations/

  fonts:
    - family: CreditCard
      fonts:
        - asset: assets/fonts/creditcard.ttf
    - family: Product
      fonts:
        - asset: assets/fonts/product.ttf
        - asset: assets/fonts/product_bold.ttf
          weight: 600
